config/routes.rb
Rails.application.routes.draw do

  root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  mount_uploader :photo, PhotoUploader
  validates :name, uniqueness:true, presence:true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail, uniqueness: {scope: :ingredient, message: "already added"}
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :cocktails, through: :doses


  validates :name, uniqueness:true, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def edit

  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

   private

    def set_restaurant
      @cokctail = Cocktail.find(params[:id])
    end

    def cocktail_params
      params.require(:cocktail).permit(:name, :photo)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end


  def destroy
    @dose = Dose.find(params[:id])
    cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(cocktail)

  end

  def create

    @dose = Dose.new(doses_params)

    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

   private

    def doses_params

      params.require(:dose).permit(:description, :ingredient_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>

  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>

<% end %>

app/views/cocktails/index.html.erb
<h1>List Of Super Cocktails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>

      <tr>
        <td><%= cocktail.name %></td>
        <td><%= link_to 'Show', cocktail %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <% if @cocktail.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @cocktail.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div>Vous voulez ajouter un nouveau cocktail?</div>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/new.html.erb
<h1>Veuillez creer un @cocktail.name</h1>
<p></p>




<%= simple_form_for @cocktail do |f| %>
<div class="form-inputs">
  <%= f.input :name %>
</div>



<div class="form-actions">
  <%= f.button :submit %>
</div>


<% end %>
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<h1>Le <%=  @cocktail.name %></h1>


<div class="container">
  <div class="row">

    <div class="col-12">
      <% @cocktail.doses.each do |dose| %>
      <div>
        <%= cl_image_tag @article.photo, height: 300, width: 400, crop: :fill %>
      </div>
      <div>
        <%= dose.ingredient.name %>
      </div>
      <div>
        <%= dose.description %>
      </div>
      <div>
        <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash destroy_dose"></i>
        <% end %>
      </div>
      <% end %>
    </div>

  </div>
</div>


<%= link_to 'Create dose', new_cocktail_dose_path(@cocktail) %>
<%= link_to 'Back', cocktails_path %>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

<div class="container">
  <div class="row">
    <div class="col-12">
    <%= simple_form_for [Cocktail.find(params[:cocktail_id]), @dose] do |f| %>

      <%= f.input :description, as: :text%>
      <%= f.input :ingredient_id, collection: Ingredient.all%>
      <%= f.submit "add a dose", class: "btn btn-primary" %>

    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>